### ISSUE TITLE
Reports' filenames

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/inventory#10]
Reports filenames look like:
- 2019-03-17T16:31:26.163593-04:00.json
- inventory_report_2019-03-17T16:31:26.163593-04:00.xlsx

Changes:
- colons and periods removed and replaced with underscores.
- Excel report does not identify which base path the report was run on (e.g., /storage/Drobo5Volume0 or /storage/Drobo5Volume1). This information should be included in the filename.

**Comment by reliztrent** [comment]
Sample XLSX file
[inventory_report_2019-03-31T16_30_15.324689-04_00.xlsx](https://github.com/gwu-libraries/audit-tool/files/3034612/inventory_report_2019-03-31T16_30_15.324689-04_00.xlsx)

**Comment by lwrubel** [comment]
@reliztrent recommends that we put the path at the front of the filename, e.g.:

Drobo5Volume0_inventory_report_2019-03-17T16_31_26_163593-04_00.xlsx
