### ISSUE TITLE
Permissions issues recurring

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/inventory#26]
Related to #8 

Attempts to manually run a new detect_changes command (which results in a new json report) or to run a new update (which results in a new inventory) both result in permissions errors.  Both commands run with account in the audit-tool group.

Permission denied errors were to a file and directory in the reports path.

Temporary workaround is currently to run a "sudo chmod" command on the offending directory/files to update permissions.

**Comment by Synkronicity** [comment]
Permissions have been updated. Manually running detect_changes no longer results in any permission denied errors
