### ISSUE TITLE
detect_changes should generate and retain excel file 

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/inventory#7]
see also #2 

Excel reports are generated by chron job that runs audits (XLSX file is emailed), but not by audit tool. 

Reasoning: Excel file is significantly easier for staff to read. When staff manually run an audit, they are supposed to review and approve it before updating the inventory. Excel file will make review more effective.

**Comment by lwrubel** [comment]
Consider adding email as an argument when manually running an audit and emailing results of manual job to one or more email addresses.

**Comment by reliztrent** [comment]
Updating REAME to note that detect_changes --excel can be used to generate excel report. 

See also #19
