### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/inventory#8]
Permissions are poorly controlled for use of audit-tool. The inventories and reports' need to have their access permissions manually changed. When the audit tool creates a new directory to hold new reports, it has the wrong access permissions.

**Comment by kilahimm** [comment]
@Synkronicity can you look at this one during the iteration to confirm new folders are inheriting permissions from parent folders appropriately?

**Comment by Synkronicity** [comment]
Changed audit-tool folder ownership from `root.domain_users` to `gwlai.digcol` [syntax = user.group]

Audit-tool should be running as user `gwlai` and any new folders it creates should reflect `gwlai.digcol` ownership
