### ISSUE TITLE
Retain Excel files

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/inventory#9]
Excel files are generated during chron job and emailed out, but not retained on the server.

**Comment by lwrubel** [comment]
No code changes needed. Using --excel with detect_changes should have the report saved to the filesystem automatically. Will test in crontab and add to prod crontab. 

Do not update crontab on prod until #19 is completed.

**Comment by lwrubel** [comment]
Updated crontab on prod to use --excel option when running detect_changes.
